name: Trigger Programmers stats Repository

on:
  push:
    branches:
      - main

jobs:
  trigger-b-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Programmers stats Repository Workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/Programmer-may/programmers-rank/dispatches \
            -d '{"event_type": "trigger-from-baekjoonhub"}'
